print('"Anyone who stops \n     learning s old, ')
print("         ",'whether at twenty')
print("               "," or e", end="")
print("i", end="")
print("g", end="")
print("h", end="")
print("t", end="")
print("y")
print("Henry Ford")